# Generated by Django 4.2.21 on 2025-06-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimSaham',
            fields=[
                ('kode_saham', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_saham', models.CharField(max_length=100)),
                ('sektor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DimWaktu',
            fields=[
                ('id_waktu', models.IntegerField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('minggu', models.IntegerField()),
                ('bulan', models.IntegerField()),
                ('tahun', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FactSaham',
            fields=[
                ('id_fakta', models.AutoField(primary_key=True, serialize=False)),
                ('harga_pembukaan', models.FloatField()),
                ('harga_penutupan', models.FloatField()),
                ('harga_tertinggi', models.FloatField()),
                ('harga_terendah', models.FloatField()),
                ('volume_transaksi', models.BigIntegerField()),
                ('id_waktu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualisasi.dimwaktu')),
                ('kode_saham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualisasi.dimsaham')),
            ],
        ),
    ]
